2023/11/15 08:03:14 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:14 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:14 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:14 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:15 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:15 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:15 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:15 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:16 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:16 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:16 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:16 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:16 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:16 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:17 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:17 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:17 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:17 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:18 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:18 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:18 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:18 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:18 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:18 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:18 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:19 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:19 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:19 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:19 [crit] 167710#167710: *22 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:19 [crit] 167710#167710: *22 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:19 [crit] 167710#167710: *22 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:19 [crit] 167710#167710: *22 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:19 [crit] 167710#167710: *22 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:19 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:19 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:19 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:20 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:20 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:20 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:20 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:20 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:20 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:20 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:21 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:21 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:21 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:21 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:22 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:22 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:22 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:22 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:22 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:22 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:22 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:22 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:22 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:22 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:22 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:23 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:23 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:23 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:23 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:23 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:23 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:23 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:03:23 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:24 [crit] 167710#167710: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:25 [crit] 167710#167710: *70 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:03:25 [crit] 167710#167710: *70 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:04:06 [crit] 167710#167710: *73 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:04:06 [crit] 167710#167710: *73 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:09:34 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:09:34 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:09:34 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:09:34 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:09:35 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:09:35 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:09:35 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:09:35 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:09:35 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:09:35 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:09:35 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:09:35 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:09:35 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:09:36 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:09:36 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:09:36 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:09:36 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:09:36 [crit] 167710#167710: *76 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:10:21 [crit] 167710#167710: *95 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 139.59.129.115, server: 0.0.0.0, request: "HEAD / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:15:27 [crit] 167710#167710: *97 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:15:27 [crit] 167710#167710: *97 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:15:27 [crit] 167710#167710: *97 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:34 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:34 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:34 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:35 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:35 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:35 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:35 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:35 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:35 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:35 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:35 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:35 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:36 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:36 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:36 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:36 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:36 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:36 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:36 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:36 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:36 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:36 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:36 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:37 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:37 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:37 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:37 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:37 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:37 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:37 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:37 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:37 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:37 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:37 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:37 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:38 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:38 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:38 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:38 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:38 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:38 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:38 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:38 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:39 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:39 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:39 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:39 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:39 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:39 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:39 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:39 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:39 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:39 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:39 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:40 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:40 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:40 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:40 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:40 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:40 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:40 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:40 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:40 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:40 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:41 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:41 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:41 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:41 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:41 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:41 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:41 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:41 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:41 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:41 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:42 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:42 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:42 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:42 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:42 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:42 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:42 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:42 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:42 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:42 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:43 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:43 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:43 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:43 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:43 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:43 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:43 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:43 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:44 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:44 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:44 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:44 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:44 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:44 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:44 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:44 [crit] 167710#167710: *101 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:45 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:45 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:45 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:45 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:45 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:45 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:45 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:46 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:46 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:46 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:46 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:46 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:46 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:46 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:47 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:47 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:47 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:47 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:47 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:47 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:47 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:47 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:48 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:48 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:48 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:48 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:48 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:48 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:48 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:49 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:49 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:50 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:50 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:50 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:50 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:51 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:51 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:51 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:51 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:52 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:52 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:52 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:52 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:53 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:53 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:53 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:53 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:53 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:54 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:54 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:54 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:54 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:54 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:55 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:55 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:55 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:55 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:55 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:55 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:56 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:56 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:56 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:56 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:57 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:57 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:57 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:57 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:57 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:58 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:58 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:58 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:58 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:58 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:59 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:59 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:59 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:59 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:18:59 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:18:59 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:19:00 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:19:00 [crit] 167710#167710: *154 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:29:29 [crit] 167710#167710: *284 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:29:29 [crit] 167710#167710: *284 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:29:29 [crit] 167710#167710: *284 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:29:29 [crit] 167710#167710: *284 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:29:29 [crit] 167710#167710: *284 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:29:30 [crit] 167710#167710: *284 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:29:30 [crit] 167710#167710: *284 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:33:32 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:33:32 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:33:32 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:33:32 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:33:32 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:33:32 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:33:32 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:33:33 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:33:33 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:33:33 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:33:33 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:33:33 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:33:33 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:33:33 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:33:33 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:33:33 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:33:35 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:33:35 [crit] 168685#168685: *1 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:37:27 [crit] 168685#168685: *21 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:37:27 [crit] 168685#168685: *21 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:37:27 [crit] 168685#168685: *21 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:37:27 [crit] 168685#168685: *21 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:37:29 [crit] 168685#168685: *21 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:37:29 [crit] 168685#168685: *21 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
2023/11/15 08:37:29 [crit] 168685#168685: *21 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:37:29 [crit] 168685#168685: *21 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:37:29 [crit] 168685#168685: *21 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET / HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/", host: "139.59.129.115:8000"
2023/11/15 08:37:29 [crit] 168685#168685: *21 connect() to unix:/home/ubuntu/django_deploy_app/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 46.165.250.77, server: 0.0.0.0, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/ubuntu/django_deploy_app/gunicorn.sock:/favicon.ico", host: "139.59.129.115:8000", referrer: "http://139.59.129.115:8000/"
